apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: nc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nc
  template:
    metadata:
      labels:
        app: nc
    spec:
      containers:
      - name: server-nc
        image: tony11111/server-nc:latest
        ports:
        - containerPort: 80

